apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64 encoded value of 'root'
  MYSQL_DATABASE: ZGV2b3Bz # base64 encoded value of 'devops'